name: "Deploy Angular Docker App"
description: "Build Angular app, create Docker image and push to registry"
inputs:
  image-name:
    description: "Docker image name"
    required: true
  registry:
    description: "Container registry (e.g. ghcr.io/username)"
    required: true
  tag:
    description: "Docker image tag"
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tag }}
